version: '3.8'

services:
  mongodb:
    image: mongo:latest
    command: mongod --port 3010
    ports:
      - "3010:3010"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--port", "3010", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
      # - nginx

  server:
    build: ./server
    ports:
      - "3011:3011"
    environment:
      - MONGODB_URI=mongodb://mongodb:3010/message-in-a-bottle
      - PORT=3011
      - BASE_PATH=/vibe-miab-server
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - default
      # - nginx

  client:
    build: ./client
    ports:
      - "3012:3012"
    environment:
      - REACT_APP_API_URL=http://localhost:3011/vibe-miab-server
      - PUBLIC_URL=/vibe-message-in-a-bottle
      - WDS_SOCKET_PORT=0
      - PORT=3012
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - default
      # - nginx

volumes:
  mongodb_data:

networks:
  default:
    name: message-in-a-bottle
  # nginx:
  #   external: true